### ISSUE TITLE
SimpleCalDav is not a constructor

### ISSUE THREAD

**Issue by tonimelisma** [TimDaub/simple-caldav#16]
When attempting to run similar example code as in the tests:

```
const { SimpleCalDav } = require("simple-caldav")

const URI = "webcal://my-fake-url"
const icloud = new SimpleCalDav(URI)

const main = async() => {
    await dav.listEvents();
}

main()
```

I just get the error ```SimpleCalDav is not a constructor```. Apologies for the basic question. Any pointers?

**Comment by TimDaub** [comment]
Try importing `SimpleCalDAV` (capitalization of DAV). Please let me know how it goes.

**Comment by tonimelisma** [comment]
A typo then 😄 Apologies for this.
