### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by jonassmedegaard** [TimDaub/simple-caldav#18]
README.md indicates tracking of some sort of "releases" - please consider applying corresponding git tags, to ease reuse, and ease issue tracking of all the feedback you get when then project becomes popular and reused by many. :-)

**Comment by TimDaub** [comment]
Hey, I tagged the last 10 releases and added a file called "PUBLISH.md" to the root. It's a specification of the package's release process. I hope that addresses your problem. Please let me know.
