### ISSUE TITLE
Summary is mandatory

### ISSUE THREAD

**Issue by chaptergy** [TimDaub/simple-caldav#23]
Hey,
I am currently creating TypeScript typings for this module, but it seems according to line https://github.com/TimDaub/simple-caldav/blob/29a11a4609ad6e547255cb5d75aa78196914b4e8/src/index.js#L193
that you have made the summary a required field while it is optional in the spec. And it seems except for this line it is optional elsewhere in your code.

**Comment by TimDaub** [comment]
Hey @chaptergy, thanks for reaching out. Also great that you're working on typings 👍🏼 

I looked into [RFC5545](https://tools.ietf.org/html/rfc5545) and found the following paragraph:

VALARM

> When the action is "EMAIL", the alarm MUST include a "DESCRIPTION" property, which contains the text to be used as the message body, a "SUMMARY" property, which contains the text to be used as the message subject, and one or more "ATTENDEE" properties, which contain the email address of attendees to receive the message.

I couldn't find mention of summary being mandatory for e.g. a VEVENT (what you were referring to). So I agree with you that it should be made optional.

It's not necessary, but do you have a reference where it explicitly says that it's optional?

**Comment by chaptergy** [comment]
I was referencing [this RFC website](https://icalendar.org/iCalendar-RFC-5545/3-6-1-event-component.html) where it says

```
; The following are OPTIONAL,
; but MUST NOT occur more than once.
;
class / created / description / geo /
last-mod / location / organizer / priority /
seq / status / summary / transp /
url / recurid /
```
