### ISSUE TITLE
Cannot use version 0.8 installed with npm

### ISSUE THREAD

**Issue by mkasprz** [TimDaub/simple-caldav#28]
I installed the version 0.8 with `npm install simple-caldav@0.8` successfully, but while building a project an error occurred:

>  error  in ./node_modules/simple-caldav/src/index.js
> 
> Module parse failed: Unexpected token (396:11)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> |         const summaryLang = alarm
> |           .getFirstProperty("summary")
> \>           ?.getParameter("language");
> |         let summary;
> | 

It seems like `?.` causes the issue (as far as I know it's not available in pure JS yet, I may be wrong though). Even after fixing the issue above, another one appears:

> |         const descLang = alarm
> |           .getFirstProperty("description")
> \>           ?.getParameter("language");
> |         let description;
> | 

I found two more places with `?.`. 

Is there something more I should install or setup, or it just needs to be changed in the code?

**Comment by TimDaub** [comment]
Yes, that's the optional chaining operator that landed in node 14: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

It looks like you're using webpack. You may have to use babel then. Otherwise simple-caldav@0.7.1 doesn't require node >= 14.

**Comment by TimDaub** [comment]
Another option to solving this solution is that we embed an esbuild process that is targeting es6 browsers

**Comment by mkasprz** [comment]
Ok, thank You. I generally have used Babel before I believe, as I had `@vue/cli-plugin-babel` installed, but I've found out that by default dependencies are not transpiled. I had to add the following to the `vue.conf.js`.
```js
module.exports = {
  // ...
  transpileDependencies: [
    'simple-caldav'
  ]
}
```

The solution You proposed seems reasonable to me. Thanks.

**Comment by TimDaub** [comment]
OK great! Feel free to close of your problem was resolved.
